//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis_ve_Urun_Takip_Sistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_TeknikServisEntities : DbContext
    {
        public Db_TeknikServisEntities()
            : base("name=Db_TeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Araclar> Tbl_Araclar { get; set; }
        public virtual DbSet<Tbl_ArizaDetay> Tbl_ArizaDetay { get; set; }
        public virtual DbSet<Tbl_Cari> Tbl_Cari { get; set; }
        public virtual DbSet<Tbl_Departman> Tbl_Departman { get; set; }
        public virtual DbSet<Tbl_FaturaBilgi> Tbl_FaturaBilgi { get; set; }
        public virtual DbSet<Tbl_FaturaDetay> Tbl_FaturaDetay { get; set; }
        public virtual DbSet<Tbl_Gider> Tbl_Gider { get; set; }
        public virtual DbSet<Tbl_Hareket> Tbl_Hareket { get; set; }
        public virtual DbSet<Tbl_Kategori> Tbl_Kategori { get; set; }
        public virtual DbSet<Tbl_Notlarim> Tbl_Notlarim { get; set; }
        public virtual DbSet<Tbl_Personel> Tbl_Personel { get; set; }
        public virtual DbSet<Tbl_Urun> Tbl_Urun { get; set; }
        public virtual DbSet<Tbl_UrunKabul> Tbl_UrunKabul { get; set; }
        public virtual DbSet<Tbl_UrunTakip> Tbl_UrunTakip { get; set; }
    }
}
