//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis_ve_Urun_Takip_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ArizaDetay
    {
        public int arizaID { get; set; }
        public Nullable<int> Islem { get; set; }
        public string Sorun { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> ortFiyat { get; set; }
        public Nullable<decimal> netFiyat { get; set; }
        public string Islemler { get; set; }
    }
}
